@echo off
setlocal enabledelayedexpansion
cd /d "%~dp0"

echo ============================================
echo  Video Downloader Pro - Build EXE
echo ============================================
echo.

REM --- Sanity checks ---------------------------------------------------
if not exist "Video_Downloader.spec" (
    echo ERROR: Video_Downloader.spec not found in this folder.
    echo Run this script from the project root ^(where main.py lives^).
    goto :fail
)

if exist "Video Downloader.spec" (
    echo NOTE: Found a second spec file: "Video Downloader.spec" ^(with a space,
    echo no underscore^). That looks auto-generated by running something like
    echo "pyinstaller main.py --name ..." directly, which does NOT include the
    echo FFmpeg bundling set up in Video_Downloader.spec ^(underscore^).
    echo.
    echo This script builds from Video_Downloader.spec ^(underscore^) on purpose -
    echo that is the one with your FFmpeg path in it. Consider deleting
    echo "Video Downloader.spec" ^(space^) so a future command can't pick it up
    echo by accident.
    echo.
)

where pyinstaller >nul 2>nul
if not errorlevel 1 (
    set "PYI_CMD=pyinstaller"
) else (
    python -m PyInstaller --version >nul 2>nul
    if not errorlevel 1 (
        set "PYI_CMD=python -m PyInstaller"
    ) else (
        py -m PyInstaller --version >nul 2>nul
        if not errorlevel 1 (
            set "PYI_CMD=py -m PyInstaller"
        )
    )
)

if not defined PYI_CMD (
    echo ERROR: PyInstaller isn't reachable via "pyinstaller", "python -m PyInstaller",
    echo or "py -m PyInstaller".
    echo Install project requirements first:  pip install -r requirements.txt
    echo If it's already installed, this usually means Python's Scripts folder
    echo isn't on PATH - try running:  python -m PyInstaller --version
    echo to confirm which command works on this machine.
    goto :fail
)
echo Using: %PYI_CMD%
echo.

set "FFMPEG_CHECK=C:\Users\steve\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-8.1.2-full_build\bin\ffmpeg.exe"
if not exist "%FFMPEG_CHECK%" (
    echo WARNING: ffmpeg.exe not found at the path baked into Video_Downloader.spec:
    echo   %FFMPEG_CHECK%
    echo.
    echo If WinGet updated FFmpeg since the spec was written ^(the version number
    echo in that path, 8.1.2, changes with each FFmpeg update^), this build will
    echo either fail or silently ship without FFmpeg bundled. Run:
    echo   where ffmpeg
    echo and update the "binaries" line near the top of Video_Downloader.spec to
    echo match the current path, then re-run this script.
    echo.
    set /p CONTINUE_ANYWAY="Continue the build anyway? (y/N): "
    if /i not "!CONTINUE_ANYWAY!"=="y" goto :fail
)

REM --- Clean previous build artifacts -----------------------------------
echo Cleaning previous build output...
if exist "dist\Video Downloader.exe" del /f /q "dist\Video Downloader.exe" >nul 2>nul
if exist "build" rmdir /s /q "build" >nul 2>nul
if exist "dist" rmdir /s /q "dist" >nul 2>nul
if exist "__pycache__" rmdir /s /q "__pycache__" >nul 2>nul

if exist "dist\Video Downloader.exe" (
    echo.
    echo ERROR: Could not delete dist\Video Downloader.exe - it is still in use.
    echo This almost always means the app is currently running.
    echo.
    echo Close "Video Downloader.exe" ^(check Task Manager and the system tray
    echo too, it may be minimized rather than fully closed^), close any Explorer
    echo window previewing the dist folder, then run this script again.
    goto :fail
)
echo.

REM --- Build --------------------------------------------------------------
echo Building with PyInstaller (Video_Downloader.spec)...
echo.
%PYI_CMD% --noconfirm "Video_Downloader.spec"
if errorlevel 1 (
    echo.
    echo ERROR: PyInstaller build failed. See output above.
    goto :fail
)

REM --- Verify output --------------------------------------------------------
if not exist "dist\Video Downloader.exe" (
    echo.
    echo ERROR: Build finished but dist\Video Downloader.exe was not created.
    goto :fail
)

echo.
echo ============================================
echo  Build succeeded: dist\Video Downloader.exe
echo ============================================
echo.
echo Next step: run build_installer.bat (or ISCC installer.iss) to package
echo the installer for distribution.
goto :end

:fail
echo.
echo Build did not complete successfully.
pause
exit /b 1

:end
pause
endlocal